server:
  addr: 127.0.0.1:8000
  

machbase:
  scheme: http
  host: 192.168.1.141
  port: 5654

watcher:
  rules:
    - source_dir: /data/cam1/in
      target_dir: /data/cam1/out
      ext: .m4s
      # prefix: 추가?

ffmpeg:
  binary: "/home/aloha/machbase/blackbox-backend/ffmpeg"

  defaults:
    input_args:
    output_args:
        # - flag: 공통 사용
          # value: 공통사용
    # output_name: "manifest.mpd"

    probe_binary: "/home/aloha/machbase/blackbox-backend/ffprobe"
    probe_args:
      - flag: v
        vlaue: "error"
      - flag: select_streams
        vlaue: "v:0"
      - flag: show_entries
        vlaue: "packet=pts_time,duration_time"
      - flag: of 
        vlaue: "csv=p=0"
      - flag: v
        vlaue: "error"
    # probe_input: "concat"

  cameras:
    - id: cam1
      rtsp_url: rtsp://machbase:machbase@192.168.1.141:554/stream1 
      output_dir: /data/cam1/in
      output_name: manifest.md

      input_args:
        - flag: rtsp_transport
          value: "tcp"
        - flag: rtsp_flags
          value: "prefer_tcp"
        - flag: buffer_size
          value: "10485760"
        - flag: max_delay
          value: "5000000"
        - flag: probesize
          value: "10000000"
        - flag: analyzeduration
          value: "10000000"
        - flag: use_wallclock_as_timestamps
          value: "1"

      mid_args:
        - flag: copyts
        - flag: c:v
          value: "copy"

      output_args:
        - flag: f
          value: dash
        - flag: seg_duration
          value: "5"
        - flag: use_template
          value: "0"
        - flag: use_timeline
          value: "0"

      extra_args: []
