server:
  addr:
  

machbase:
  scheme: http
  host: 127.0.0.1
  port: 5654

watcher:
  rules:
    - source_dir: /data/cam1/in
      target_dir: /data/cam1/out
      ext: .m4s

ffmpeg:
  binary: ./ffmpeg

  cameras:
    - id: cam1
      rtsp_url: "rtsp://user:pa ss@10.0.0.11/stream1"   # 공백 포함(비번)
      output_dir: "/data/cam 1"                          # 공백 포함 경로
      output_name: "manifest.mpd"

      input_args:
        - flag: rtsp_transport
          value: "tcp"
        - flag: rtsp_flags
          value: "prefer_tcp"
        - flag: buffer_size
          value: "10485760"
        - flag: max_delay
          value: "5000000"
        - flag: probesize
          value: "10000000"
        - flag: analyzeduration
          value: "10000000"
        - flag: use_wallclock_as_timestamps
          value: "1"

      mid_args:
        - flag: copyts
        - flag: c:v
          value: "copy"

      output_args:
        - flag: f
          value: "dash"
        - flag: seg_duration
          value: "5"
        - flag: use_template
          value: "0"
        - flag: use_timeline
          value: "0"

      # shellQuote 효과를 더 보여주려고 일부러 복잡한 값 넣음(예시)
      extra_args:
        - flag: metadata
          value: "title=O'Reilly demo"        # 작은따옴표 포함
        - flag: headers
          value: "User-Agent: My Agent/1.0"   # 공백 포함
        - flag: loglevel
          value: "warning"
